### ISSUE TITLE
Error when running node test.js

### ISSUE THREAD

**Issue by navinp0304** [VishwaGauravIn/linkedin-jobs-api#3]
I get below error when running node test.js 
```
home/navin/js/linkedin-jobs-api/index.js:16
  this.keyword = queryObj.keyword?.replace(" ", "+") || "";
                                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/navin/js/linkedin-jobs-api/test.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by VishwaGauravIn** [comment]
Hi @navinp0304 
Thanks for raising this issue, it has been fixed.
Please try updating it now.

**Comment by navinp0304** [comment]
Still not working.
```

node test.js 
/home/navin/js/linkedin-jobs-api/index.js:16
  this.keyword = queryObj.keyword?.trim().replace(" ", "+") || "";
                                  ^

SyntaxError: Unexpected token '.'
```

**Comment by VishwaGauravIn** [comment]
can you please share a screen recording? Showing what you are trying to do, the test code and index code

**Comment by navinp0304** [comment]
![image](https://github.com/VishwaGauravIn/linkedin-jobs-api/assets/74448943/f1d0f59f-157e-418f-96c9-d7ff861c9c82)

**Comment by navinp0304** [comment]
Looks like my nodejs was old version 12 which i got by install apt-get install nodejs
