### ISSUE TITLE
Error importing module

### ISSUE THREAD

**Issue by amit4317** [VishwaGauravIn/linkedin-jobs-api#6]
/home/ak/node_modules/linkedin-jobs-api/index.js:16
  this.keyword = queryObj.keyword?.trim().replace(" ", "+") || "";
                                  ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ak/lkdn_japi/job.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by amit4317** [comment]
Fixed it. Just update node with nvm.
